#define STATE_Xr1 0
#define STATE_Xr2 1
#define STATE_Xs 2
#define STATE_m 3
#define STATE_h 4
#define STATE_j 5
#define STATE_d 6
#define STATE_f 7
#define STATE_f2 8
#define STATE_fCass 9
#define STATE_s 10
#define STATE_r 11
#define STATE_Ca_SR 12
#define STATE_Ca_i 13
#define STATE_Ca_ss 14
#define STATE_R_prime 15
#define STATE_Na_i 16
#define STATE_V 17
#define STATE_K_i 18
#define NUM_STATES 19

#define PARAM_P_kna 0
#define PARAM_g_K1 1
#define PARAM_g_Kr 2
#define PARAM_g_Ks 3
#define PARAM_g_Na 4
#define PARAM_g_bna 5
#define PARAM_g_CaL 6
#define PARAM_g_bca 7
#define PARAM_g_to 8
#define PARAM_K_mNa 9
#define PARAM_K_mk 10
#define PARAM_P_NaK 11
#define PARAM_K_NaCa 12
#define PARAM_K_sat 13
#define PARAM_Km_Ca 14
#define PARAM_Km_Nai 15
#define PARAM_alpha 16
#define PARAM_gamma 17
#define PARAM_K_pCa 18
#define PARAM_g_pCa 19
#define PARAM_g_pK 20
#define PARAM_Buf_c 21
#define PARAM_Buf_sr 22
#define PARAM_Buf_ss 23
#define PARAM_Ca_o 24
#define PARAM_EC 25
#define PARAM_K_buf_c 26
#define PARAM_K_buf_sr 27
#define PARAM_K_buf_ss 28
#define PARAM_K_up 29
#define PARAM_V_leak 30
#define PARAM_V_rel 31
#define PARAM_V_sr 32
#define PARAM_V_ss 33
#define PARAM_V_xfer 34 
#define PARAM_Vmax_up 35 
#define PARAM_k1_prime 36
#define PARAM_k2_prime 37
#define PARAM_k3 38
#define PARAM_k4 39
#define PARAM_max_sr 40
#define PARAM_min_sr 41
#define PARAM_Na_o 42
#define PARAM_Cm 43
#define PARAM_F 44
#define PARAM_R 45
#define PARAM_T 46
#define PARAM_V_c 47
#define PARAM_stim_amplitude 48
#define PARAM_stim_duration 49
#define PARAM_stim_period 50
#define PARAM_stim_start 51
#define PARAM_K_o 52
#define NUM_PARAMS 53